spring:
  application:
    name: transaction-account

  # JPA
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_account
    username: root
    password: ""
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  # Flyway
  flyway:
    baseline-on-migrate: true

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bank-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    filter: true
    display-operation-id: true
    display-request-duration: true

# Server
server:
  error:
    include-stacktrace: never

# Logs
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

# API
api:
  prefix: /api/v1

